# Generated by Django 5.2.7 on 2025-10-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='系列名称')),
                ('description', models.TextField(verbose_name='系列描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='series_images/', verbose_name='系列图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备系列',
                'verbose_name_plural': '设备系列',
                'ordering': ['created_at'],
            },
        ),
    ]
